### ISSUE TITLE
spf plugin ran callback multiple times 

### ISSUE THREAD

**Issue by celesteking** [baudehlo/Haraka#1111]
Don't know why it's happening, but here's the log. No detailed info available.
```
Aug 21 10:24:48 dev3 haraka[5877]: [INFO] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [spf] identity=mfrom ip=209.202.107.210 domain="enbridgegas.com" mfrom=<customercare@enbridgegas.com> result=TempError
Aug 21 10:24:48 dev3 haraka[5877]: [INFO] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [spf] scope: mfrom, result: TempError, domain: enbridgegas.com
Aug 21 10:24:48 dev3 haraka[5877]: [INFO] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [greylist] Requested to skip the GL because skip rule matched: dnswl.org(MED)
Aug 21 10:24:48 dev3 haraka[5877]: [INFO] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [karma] applied results.spf.result:-2
Aug 21 10:24:48 dev3 haraka[5877]: [INFO] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [karma] connect: -2, history: 23, total_connects: 77, fail:spf.result, skip:penalty
Aug 21 10:24:48 dev3 haraka[5877]: [INFO] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [spf] identity=mfrom ip=209.202.107.210 domain="enbridgegas.com" mfrom=<customercare@enbridgegas.com> result=TempError
Aug 21 10:24:48 dev3 haraka[5877]: [INFO] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [spf] scope: mfrom, result: TempError, domain: enbridgegas.com

Aug 21 10:24:48 dev3 haraka[5877]: [ERROR] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [core] spf plugin ran callback multiple times - ignoring subsequent calls
Aug 21 10:24:48 dev3 haraka[5877]: [ERROR] [2902D24F-8F83-4EAD-8A6C-8F4A8134AE6E.1] [core] Error
Aug 21 10:24:48 dev3 at callback (/home/haraka/nodejs/node_modules/Haraka/plugins.js:285:34)
Aug 21 10:24:48 dev3 at Plugin.exports.return_results (/home/haraka/nodejs/node_modules/Haraka/plugins/spf.js:251:20)
Aug 21 10:24:48 dev3 at ch_cb (/home/haraka/nodejs/node_modules/Haraka/plugins/spf.js:187:23)
Aug 21 10:24:48 dev3 at mech_chain_caller (/home/haraka/nodejs/node_modules/Haraka/spf.js:311:24)
Aug 21 10:24:48 dev3 at /home/haraka/nodejs/node_modules/Haraka/spf.js:496:52
Aug 21 10:24:48 dev3 at Object.asyncCallback [as callback] (dns.js:81:16)
Aug 21 10:24:48 dev3 at Object.onresolve [as oncomplete] (dns.js:199:10)
```

**Comment by smfreegard** [comment]
Sorry - but you'll have to upgrade your spf plugin to match the version in git master as the line numbers do not correspond to it.
