### ISSUE TITLE
Haraka fails to install on Ubuntu 14.10

### ISSUE THREAD

**Issue by steowens** [baudehlo/Haraka#855]
```
root@mail:~# npm install -g Haraka
/
> node-syslog@1.1.7 install /usr/lib/node_modules/Haraka/node_modules/node-syslog
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/node-syslog/.node-gyp"
make: Entering directory `/usr/lib/node_modules/Haraka/node_modules/node-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
make: g++: Command not found
make: *** [Release/obj.target/syslog/syslog.o] Error 127
make: Leaving directory `/usr/lib/node_modules/Haraka/node_modules/node-syslog/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab094.7
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/node-syslog
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing node-syslog@1.1.7

> dtrace-provider@0.2.8 install /usr/lib/node_modules/Haraka/node_modules/ldapjs/node_modules/dtrace-provider
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/ldapjs/node_modules/dtrace-provider/.node-gyp"
make: Entering directory `/usr/lib/node_modules/Haraka/node_modules/ldapjs/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/usr/lib/node_modules/Haraka/node_modules/ldapjs/node_modules/dtrace-provider/build'

> iconv@2.1.6 install /usr/lib/node_modules/Haraka/node_modules/iconv
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/iconv/.node-gyp"
make: Entering directory `/usr/lib/node_modules/Haraka/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
make: cc: Command not found
make: *** [Release/obj.target/libiconv/deps/libiconv/lib/iconv.o] Error 127
make: Leaving directory `/usr/lib/node_modules/Haraka/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab094.7
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/iconv
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! iconv@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.6 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-042stab094.7
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "Haraka"
npm ERR! cwd /root
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
root@mail:~# ls -al /root
total 52
drwx------  7 root root 4096 Feb 21 19:18 .
drwxr-xr-x 21 root root 4096 Feb 21 02:02 ..
-rw-------  1 root root 2747 Feb 21 15:54 .bash_history
-rw-r--r--  1 root root 3106 Feb 19  2014 .bashrc
drwx------  2 root root 4096 Feb 21 12:21 .cache
drwxr-xr-x  3 root root 4096 Feb 21 19:13 .node-gyp
drwxr-xr-x 90 root root 4096 Feb 21 19:18 .npm
-rw-r--r--  1 root root  140 Feb 19  2014 .profile
-rw-------  1 root root 4975 Feb 21 13:54 .viminfo
-rwxr--r--  1 root root 1121 Feb 21 12:23 bootstrap.sh
drwxr-xr-x  2 root root 4096 Feb 21 12:34 mailinabox
drwxr-xr-x  4 root root 4096 Feb 21 19:13 node_modules
root@mail:~# 
```

**Comment by baudehlo** [comment]
You need to install gcc or clang first. The dependent modules are compiled so you need a compiler.

**Comment by steowens** [comment]
That wasn't the problem,  apparently there was a reference to a repo for yunohost.org that when I deleted the reference and reinstalled node and node-gyp, I was able to complete the install of haraka.  However it still issues these warnings:

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/node-syslog/.node-gyp"


Might be worth while to look into this.

**Comment by baudehlo** [comment]
That's more of a permission problem on your end I think.

**Comment by steowens** [comment]
I am not sure what permissions I would need.  I was running the command as root, and the folders that it is discussing are owned by root.

**Comment by baudehlo** [comment]
I'm equally confused. But my guess is that npm drops privileges somewhere and thus can't write to whatever folder it is.

What version of npm are you on? I've had some weird problems until I upgraded npm.

**Comment by steowens** [comment]
I am using 1.3.24

**Comment by baudehlo** [comment]
Definitely worth upgrading.
