### ISSUE TITLE
some bug in http or whatever

### ISSUE THREAD

**Issue by celesteking** [baudehlo/Haraka#987]
master branch, but some configs maybe outdated, it's moving too fast to keep track of everything.
```
[NOTICE] [-] [core] Listening on :::2525
[NOTICE] [-] [core] Listening on :::2587
[DEBUG] [-] [server] running init_master hooks
[DEBUG] [-] [server] running init_master hook in redis plugin
[NOTICE] [-] [core] Listening on 127.0.0.1:8010
[DEBUG] [-] [server] running init_http hooks
[CRIT] [-] [core] Error: We are already running hooks! Fatal error!
[CRIT] [-] [core]     at Object.plugins.run_hooks (/storage/personal/work/coding/ruby/nodejs/node_modules/Haraka/plugins.js:233:15)
[CRIT] [-] [core]     at registerRoutes (/storage/personal/work/coding/ruby/nodejs/node_modules/Haraka/server.js:283:17)
[CRIT] [-] [core]     at done (/storage/personal/work/coding/ruby/nodejs/node_modules/Haraka/node_modules/async/lib/async.js:132:19)
[CRIT] [-] [core]     at /storage/personal/work/coding/ruby/nodejs/node_modules/Haraka/node_modules/async/lib/async.js:32:16
[CRIT] [-] [core]     at Server.<anonymous> (/storage/personal/work/coding/ruby/nodejs/node_modules/Haraka/server.js:270:13)
[CRIT] [-] [core]     at Server.emit (events.js:92:17)
[CRIT] [-] [core]     at net.js:1055:10
[CRIT] [-] [core]     at process._tickCallback (node.js:419:13)
[CRIT] [-] [core]     at Function.Module.runMain (module.js:499:11)
[CRIT] [-] [core]     at startup (node.js:119:16)
[NOTICE] [-] [core] Shutting down
```

**Comment by msimerson** [comment]
please also provide config/plugins. It appears you have something other than master loading, such as an old version of watch?

**Comment by celesteking** [comment]
watch has been commented out. I'm on master branch.  [see  here](https://gist.github.com/celesteking/f2ea9c60ed292cbcdffa)

**Comment by msimerson** [comment]
````
[root@haraka] # cd /usr/local/lib/node_modules/
[root@haraka] # git clone https://github.com/baudehlo/Haraka.git
Cloning into 'Haraka'...
<snip>
Checking connectivity... done.
[root@haraka] # cd Haraka
[root@haraka] # npm install
<snip lots of output>
[root@haraka] # haraka -i /usr/local/haraka
[root@haraka] # cd /usr/local/haraka
[root@haraka] # sed -i .bak -e 's/^;listen=\[.*$/listen=127.0.0.9:25,127.0.0.9:465,127.0.0.9:587/' config/smtp.ini
[root@haraka] # sed -i .bak -e 's/; listen=\[::\]:80/listen=127.0.0.9:80/' config/http.ini
[root@haraka] # haraka -c /usr/local/haraka
loglevel: LOGPROTOCOL
Starting up Haraka version 2.6.1
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: access
[DEBUG] [-] [core] no timeout in access.timeout
[DEBUG] [-] [core] no timeout in plugin_timeout
[DEBUG] [-] [core] plugin access timeout is: 30s
[INFO] [-] [core] loaded 7185 Public Suffixes
<snip>
[DEBUG] [-] [core] registered hook connect to max_unrecognized_commands.hook_connect
[DEBUG] [-] [core] registered hook unrecognized_command to max_unrecognized_commands.hook_unrecognized_command
[ERROR] [-] [core] Missing tls_key.pem for port 465
[NOTICE] [-] [core] Listening on 127.0.0.9:25
[NOTICE] [-] [core] Listening on 127.0.0.9:587
[DEBUG] [-] [server] running init_master hooks
[INFO] [-] [core] [outbound] Loading outbound queue from /usr/local/haraka/queue
[NOTICE] [-] [core] Listening on 127.0.0.9:80
[DEBUG] [-] [server] running init_http hooks
[DEBUG] [-] [server] running init_wss hooks
[INFO] [-] [core] using html docroot: /usr/local/haraka/html
[DEBUG] [-] [dnsbl] looking up: 2.0.0.127.zen.spamhaus.org.
^C
[NOTICE] [-] [core] SIGINT received
[NOTICE] [-] [core] Shutting down
[root@haraka] # echo 'watch' >> config/plugins 
[root@haraka] # haraka -c /usr/local/haraka
loglevel: LOGPROTOCOL
Starting up Haraka version 2.6.1
[INFO] [-] [core] Loading plugins
<snip>
[DEBUG] [-] [server] running init_master hooks
[INFO] [-] [core] [outbound] Loading outbound queue from /usr/local/haraka/queue
[NOTICE] [-] [core] Listening on 127.0.0.9:80
[DEBUG] [-] [server] running init_http hooks
[DEBUG] [-] [server] running init_http hook in watch plugin
[DEBUG] [-] [server] hook=init_http plugin=watch function=hook_init_http params="undefined" retval=CONT msg=""
[DEBUG] [-] [server] running init_wss hooks
[DEBUG] [-] [server] running init_wss hook in watch plugin
[DEBUG] [-] [server] hook=init_wss plugin=watch function=hook_init_wss params="undefined" retval=CONT msg=""
[INFO] [-] [core] using html docroot: /usr/local/haraka/html
[DEBUG] [-] [dnsbl] looking up: 2.0.0.127.zen.spamhaus.org.
````

Works as expected here. I'd recommend starting with a stock Haraka and then introducing your customizations, one at a time until you figure out where the issue lies.

**Comment by celesteking** [comment]
Nah, that's not gonna happen, it's just too many of them. You'd better tell fortunes by looking at that stacktrace, I'm sure you know better than me what's causing it. 

I've got an old karma plugin, btw.

**Comment by msimerson** [comment]
>  I'm sure you know better than me what's causing it.

I don't know, but try updating your log.elasticsearch plugin with the latest edition in the PR.

**Comment by celesteking** [comment]
Okay, this plugin is heavily unripe. 

I enabled watch, getting now: 
watchers.
[object Event], undefined[object Event], undefined[object Event], 

AND in chrome console:
XHR finished loading: GET "http://localhost:8010/watch/wss_conf".
client.js:182 WebSocket connection to 'wss://localhost:8010/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

You should really provide install instructions for that.

**Comment by celesteking** [comment]
Now regarding the error. It's caused by enabling my redis plugin that works perfectly without http being enabled. 

Could it be that init_master is not reenterable? Here's the code:

```js
exports.register = function () {
    var plugin = this;

    this.register_hook('init_master',  'redis_onInit');
//    this.register_hook('init_child',   'redis_onInit');
};
exports.redis_onInit = function (next, server) {
    if (server.notes.redis)
        return next();

    var redis = require('redis');
    var plugin = this;
    var config = this.config.get('redis.ini');

    var r_opts = {
    	//connect_timeout: 1000
    };

    var next_called;

    (server.notes.redis = redis.createClient(config.main.port, config.main.host, r_opts))
        .on('error', function (err) {
            plugin.logerror("Redis error: " + err + '. Reconnecting...');
//            if (server.notes.redis) {
//                server.notes.redis.quit(); // FIXME: is this needed?
//            }
        })
        .on('ready', function(){
            plugin.loginfo('Redis connected to ' + server.notes.redis.host + ':' + (server.notes.redis.port ||0 ) +
                    '/' +  (config.main.db || 0 ) + ' v' + server.notes.redis.server_info.redis_version);

            if (config.main.db) {
                server.notes.redis.select(config.main.db, function(){
                    if (!next_called) {
                        next_called = true;
                        return next();
                    }
                })
            } else {
                if (!next_called) {
                    next_called = true;
                    return next();
                }
            }
        });
};
```

Usually, log looks like this:
```
[DEBUG] [-] [server] running init_master hooks
[DEBUG] [-] [server] running init_master hook in redis plugin
[INFO] [-] [redis] Redis connected to localhost:6379/1 v2.8.8
[DEBUG] [-] [server] hook=init_master plugin=redis function=redis_onInit params="" retval=CONT msg=""
```

With http, it looks:
```
[DEBUG] [-] [server] running init_master hooks
[DEBUG] [-] [server] running init_master hook in redis plugin
[NOTICE] [-] [core] Listening on 127.0.0.1:8010
[DEBUG] [-] [server] running init_http hooks
[CRIT] [-] [core] Error: We are already running hooks! Fatal error!
```

So master hook is entered in redis, then the hook is being run in http? And then a crash?
What do you think? 

I commented out ```init_child``` to pinpoint the issue to master hook. If I don't hook on master and leave child hook, everything works fine.

**Comment by celesteking** [comment]
More than that, it appears the same is happening with my other plugins that use init_master. 
Please, explain what's the current method of dealing with clustered / singlechild iniitalization hooks?

**Comment by celesteking** [comment]
Hooks are commented out, so I guess I'm not the only one having issues with master/child hooks.

https://github.com/msimerson/Haraka/blob/8a319e3312220d01c973bfca8feb502343320b95/plugins/watch/index.js#L16-L17

What's the proper way of initializing plugin state now? For ex., I want to init redis clients: one per each node child.

**Comment by msimerson** [comment]
> Hooks are commented out, so I guess I'm not the only one having issues with master/child hooks.

No sir, that is completely not the case. Those hooks are commented out because `watch` **used** to have it's own built-in HTTP server. The [HTTP server is now built-in to Haraka](baudehlo/haraka#914), so watch now gets requests on the init_http hook (a few lines down).

**Comment by smfreegard** [comment]
I think the issue here is that the init_http and init_wss hooks are trying to run at the same time as init_master/init_child and that's why it's blowing up as the plugin running expects hooks to run one at a time by default.

**Comment by celesteking** [comment]
It blows up when not run in cluster mode, too. 

It's a total clusterfuck.

**Comment by smfreegard** [comment]
Here's your test case @msimerson:

`````javascript
exports.hook_init_master = exports.hook_init_child = function (next) {
    setImmediate(function () { return next(); });
}
`````

That should reliably explode Haraka if you enable the HTTP server.

**Comment by celesteking** [comment]
And there's also a funny comment in log.es plugin. And of course, that needs to be fixed too, guys ;)
```javascript
    // hook reset_transaction doesn't seem to wait for next(). If I
    // wait until after I get a response back from ES, Haraka throws
    // "Error: We are already running hooks!". So we record that we've sent
    // to ES (so connection isn't saved too) and hope for the best.
    connection.notes.elasticsearch=connection.tran_count;
```

**Comment by celesteking** [comment]
Just realized this would trigger it too: ``` exports.hook_init_master = exports.hook_init_child = function (next) { };```

**Comment by smfreegard** [comment]
That's only because you've got other things running on the same hook.

If you create config/plugins with only this plugin enabled - it will fail:

`````javascript
exports.register = function () {
    this.register_hook('init_master', 'foo');
    this.register_hook('init_master', 'foo1');
}

exports.foo = exports.foo1 = function (next) {
    process.nextTick(function () { return next(); });
}

exports.hook_init_http = function (next) {
    return next();
}
`````

**Comment by msimerson** [comment]
So which is the right solution?

1. allow those hooks to run at the same time (modify plugins.js)
2. have init_master and init_child run the http hooks in init_____respond

**Comment by baudehlo** [comment]
The latter.

**Comment by celesteking** [comment]
I'm lost in these commits. Which ones should I try?

**Comment by smfreegard** [comment]
@cek #1015

**Comment by celesteking** [comment]
You should stop doing commits against master and instead do them against long term support branch. There's too much to merge/cherry-pick for me in order to get up to that change.

**Comment by msimerson** [comment]
> You should stop doing commits against master 

I want the new feature(s), but can you stop changing stuff?  Makes perfect sense to me.

**Comment by celesteking** [comment]
This feature requires connection.js & server.js patched, that's all. Why should I pull another gazzilion of plugin and unrelated stuff changes?

**Comment by celesteking** [comment]
```
[DEBUG] [-] [server] running init_http hooks
[DEBUG] [-] [server] running init_http hook in watch plugin
[CRIT] [-] [server] Plugin watch failed: TypeError: Cannot call method 'use' of undefined
    at Plugin.exports.hook_init_http (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins/watch/index.js:44:9)
    at Object.plugins.run_next_hook (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:371:28)
    at Object.plugins.run_hooks (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:288:13)
    at Object.Server.init_master_respond (/storage/personal/work/coding/nodejs/node_modules/Haraka/server.js:305:17)
    at callback (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:345:35)
    at /storage/personal/work/coding/nodejs/hk/plugins/auth/auth_anti_brute.js:26:27
    at _fulfilled (/storage/personal/work/coding/nodejs/node_modules/Haraka/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/storage/personal/work/coding/nodejs/node_modules/Haraka/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/storage/personal/work/coding/nodejs/node_modules/Haraka/node_modules/q/q.js:756:13)
    at /storage/personal/work/coding/nodejs/node_modules/Haraka/node_modules/q/q.js:564:44
[DEBUG] [-] [server] hook=init_http plugin=watch function=hook_init_http params="" retval=CONT msg=""
[INFO] [-] [core] init_http_respond
[INFO] [-] [core] Server.http.wss loaded
[DEBUG] [-] [server] running init_wss hooks
[DEBUG] [-] [server] running init_wss hook in watch plugin
[CRIT] [-] [server] Plugin watch failed: TypeError: Cannot call method 'on' of undefined
    at Plugin.exports.hook_init_wss (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins/watch/index.js:70:9)
    at Object.plugins.run_next_hook (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:371:28)
    at Object.plugins.run_hooks (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:288:13)
    at Object.Server.init_http_respond (/storage/personal/work/coding/nodejs/node_modules/Haraka/server.js:416:13)
    at callback (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:345:35)
    at Object.plugins.run_next_hook (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:378:9)
    at Object.plugins.run_hooks (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:288:13)
    at Object.Server.init_master_respond (/storage/personal/work/coding/nodejs/node_modules/Haraka/server.js:305:17)
    at callback (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:345:35)
    at /storage/personal/work/coding/nodejs/hk/plugins/auth/auth_anti_brute.js:26:27
[DEBUG] [-] [server] hook=init_wss plugin=watch function=hook_init_wss params="" retval=CONT msg=""
[INFO] [-] [core] init_wss_respond
[NOTICE] [-] [core] Listening on 127.0.0.1:8010
[DEBUG] [-] [dnsbl] looking up: 2.0.0.127.xbl.spamhaus.org.
[DEBUG] [-] [dnsbl] looking up: 2.0.0.127.sbl.spamhaus.org.
^C[NOTICE] [-] [core] SIGINT received
[NOTICE] [-] [core] Shutting down
```

More than that, I can't disable it commenting out  ;listen = 127.0.0.1:8010:
```
[INFO] [-] [core] init_http_respond
[CRIT] [-] [core] TypeError: `port` or a `server` must be provided
[CRIT] [-] [core]     at new WebSocketServer (/storage/personal/work/coding/nodejs/node_modules/Haraka/node_modules/ws/lib/WebSocketServer.js:39:11)
[CRIT] [-] [core]     at Object.Server.init_http_respond (/storage/personal/work/coding/nodejs/node_modules/Haraka/server.js:413:23)
[CRIT] [-] [core]     at callback (/storage/personal/work/coding/nodejs/node_modules/Haraka/plugins.js:345:35)
```

**Comment by msimerson** [comment]
You'll need to disable the watch plugin, as the API for http changed a little. Once this PR lands, I can land the updates for watch.

**Comment by cek** [comment]
I don't know why I'm on this thread, but I'd love not to be. :)

**Comment by celesteking** [comment]
@cek how much for the handle?!

**Comment by msimerson** [comment]
> I don't know why I'm on this thread, but I'd love not to be. :)

I updated @smfreegard 's reference to point to his intended victim. Now, if you @cek will visit the little Notifications button to the right side of this conversation, and click the Unsubscribe button, I think you'll find it Does The Needful.

**Comment by cek** [comment]
Ha, thanks much.  I raised my handle from a pup, no desire to send it to a foster home.
